spring.application.name=clinica

server.servlet.context-path=/api

# Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_estetica
spring.datasource.username=app_clinica
spring.datasource.password=Clinica2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate e Schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=clinica

# Configuração do Flyway (Substitui o Liquibase)
spring.flyway.schemas=clinica

# Solução para o erro "Unsupported Database: PostgreSQL 18.2"
# Diz ao Flyway para aceitar bases de dados mais recentes do que a versão dele
spring.flyway.ignore-missing-migrations=true

# Segurança e JWT
api.security.token.secret=hOYF+u2/E+2EJE2j3sOt+86pIbUBsQ9rsynQM7Qmfew=
spring.web.error.include-stacktrace=always