url=jdbc:postgresql://localhost:5432/clinica_estetica
username=app_clinica
password=Clinica2026!
defaultSchemaName=clinica

referenceUrl=hibernate:spring:com.cljtech.clinica?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
driver=org.postgresql.Driver

outputChangeLogFile=src/main/resources/db/changelog/generated/001-generated-changelog.yaml