-- 1. TABELAS INDEPENDENTES BASE (CRIADAS PRIMEIRO)
CREATE TABLE clinica.usuarios
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao          TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao      TIMESTAMP WITHOUT TIME ZONE,
    ativo                 BOOLEAN,
    login                 VARCHAR(255)                            NOT NULL,
    senha                 VARCHAR(255)                            NOT NULL,
    nome                  VARCHAR(255)                            NOT NULL,
    email                 VARCHAR(255),
    perfil                VARCHAR(255),
    registro_profissional VARCHAR(255),
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uc_usuarios_login UNIQUE (login)
);

CREATE TABLE clinica.pessoa
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    nome             VARCHAR(255),
    cpf              VARCHAR(255),
    email            VARCHAR(255),
    telefone         VARCHAR(255),
    data_nascimento  DATE,
    logradouro       VARCHAR(255),
    numero           VARCHAR(255),
    complemento      VARCHAR(255),
    bairro           VARCHAR(255),
    cidade           VARCHAR(255),
    estado           VARCHAR(255),
    cep              VARCHAR(255),
    CONSTRAINT pk_pessoa PRIMARY KEY (id),
    CONSTRAINT uc_pessoa_cpf UNIQUE (cpf)
);

CREATE TABLE clinica.procedimento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    nome             VARCHAR(255)                            NOT NULL,
    preco_sugerido   DECIMAL,
    duracao_minutos  INTEGER,
    CONSTRAINT pk_procedimento PRIMARY KEY (id),
    CONSTRAINT uc_procedimento_nome UNIQUE (nome)
);

CREATE TABLE clinica.paciente
(
    id                 BIGINT NOT NULL,
    observacoes_gerais VARCHAR(255),
    tipo_sanguineo     VARCHAR(255),
    nome_responsavel   VARCHAR(255),
    CONSTRAINT pk_paciente PRIMARY KEY (id),
    CONSTRAINT FK_PACIENTE_ON_ID FOREIGN KEY (id) REFERENCES clinica.pessoa (id)
);

CREATE TABLE clinica.insumo
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao       TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao   TIMESTAMP WITHOUT TIME ZONE,
    ativo              BOOLEAN,
    nome               VARCHAR(255),
    quantidade_estoque DOUBLE PRECISION,
    unidade_medida     VARCHAR(255),
    CONSTRAINT pk_insumo PRIMARY KEY (id)
);

CREATE TABLE clinica.local_aplicacao
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    nome             VARCHAR(255)                            NOT NULL,
    pre_definido     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_localaplicacao PRIMARY KEY (id),
    CONSTRAINT uc_localaplicacao_nome UNIQUE (nome)
);

-- 2. TABELAS QUE DEPENDEM DE USUARIOS E PACIENTES
-- 1. Tabela agendamento atualizada (SEM a coluna procedimento_id e SEM a FK antiga)
CREATE TABLE clinica.agendamento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    paciente_id      BIGINT                                  NOT NULL,
    profissional_id  BIGINT                                  NOT NULL,
    data_hora_inicio TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    data_hora_fim    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status           VARCHAR(255),
    motivo_consulta  VARCHAR(255),
    valor_previsto   DECIMAL,
    CONSTRAINT pk_agendamento PRIMARY KEY (id),
    CONSTRAINT FK_AGENDAMENTO_ON_PACIENTE FOREIGN KEY (paciente_id) REFERENCES clinica.paciente (id),
    CONSTRAINT FK_AGENDAMENTO_ON_PROFISSIONAL FOREIGN KEY (profissional_id) REFERENCES clinica.usuarios (id)
);

CREATE TABLE clinica.agendamento_procedimento (
                                                  agendamento_id BIGINT NOT NULL,
                                                  procedimento_id BIGINT NOT NULL,
                                                  CONSTRAINT pk_agendamento_procedimento PRIMARY KEY (agendamento_id, procedimento_id),
                                                  CONSTRAINT fk_agend_proc_agendamento FOREIGN KEY (agendamento_id) REFERENCES clinica.agendamento (id) ON DELETE CASCADE,
                                                  CONSTRAINT fk_agend_proc_procedimento FOREIGN KEY (procedimento_id) REFERENCES clinica.procedimento (id)
);

CREATE TABLE clinica.evolucoes_clinicas
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao           TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao       TIMESTAMP WITHOUT TIME ZONE,
    ativo                  BOOLEAN,
    agendamento_id         BIGINT                                  NOT NULL,
    paciente_id            BIGINT                                  NOT NULL,
    profissional_id        BIGINT                                  NOT NULL,
    data_registro          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    relato_clinico         TEXT                                    NOT NULL,
    diagnostico_hipotetico VARCHAR(255),
    CONSTRAINT pk_evolucoes_clinicas PRIMARY KEY (id),
    CONSTRAINT uc_evolucoes_clinicas_agendamento UNIQUE (agendamento_id),
    CONSTRAINT FK_EVOLUCOES_CLINICAS_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES clinica.agendamento (id),
    CONSTRAINT FK_EVOLUCOES_CLINICAS_ON_PACIENTE FOREIGN KEY (paciente_id) REFERENCES clinica.paciente (id),
    CONSTRAINT FK_EVOLUCOES_CLINICAS_ON_PROFISSIONAL FOREIGN KEY (profissional_id) REFERENCES clinica.usuarios (id)
);

CREATE TABLE clinica.evolucoes_esteticas
(
    id               BIGINT NOT NULL,
    numero_sessao    INTEGER,
    dose_aplicada_mg DOUBLE PRECISION,
    peso_paciente_kg DOUBLE PRECISION,
    CONSTRAINT pk_evolucoes_esteticas PRIMARY KEY (id),
    CONSTRAINT FK_EVOLUCOES_ESTETICAS_ON_ID FOREIGN KEY (id) REFERENCES clinica.evolucoes_clinicas (id)
);

CREATE TABLE clinica.evolucao_locais
(
    evolucao_id BIGINT NOT NULL,
    local_id    BIGINT NOT NULL,
    CONSTRAINT fk_evoloc_on_evolucao_estetica FOREIGN KEY (evolucao_id) REFERENCES clinica.evolucoes_esteticas (id),
    CONSTRAINT fk_evoloc_on_local_aplicacao FOREIGN KEY (local_id) REFERENCES clinica.local_aplicacao (id)
);

-- Criar a tabela de consumo de insumos atrelada ao schema clinica
CREATE TABLE clinica.consumos_insumos (
                                          id BIGSERIAL NOT NULL,
                                          evolucao_id BIGINT NOT NULL,
                                          insumo_id BIGINT NOT NULL,
                                          quantidade_usada NUMERIC(19, 2) NOT NULL,
                                          data_consumo TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Chave Primária
                                          CONSTRAINT pk_consumos_insumos PRIMARY KEY (id),

    -- Chave Estrangeira para a tabela Pai (Evoluções Clínicas)
                                          CONSTRAINT fk_consumo_evolucao
                                              FOREIGN KEY (evolucao_id)
                                                  REFERENCES clinica.evolucoes_clinicas (id)
                                                  ON DELETE RESTRICT,

    -- Chave Estrangeira para a tabela de Insumos (CORRIGIDO PARA SINGULAR)
                                          CONSTRAINT fk_consumo_insumo
                                              FOREIGN KEY (insumo_id)
                                                  REFERENCES clinica.insumo (id) -- <--- Mudado aqui de 'insumos' para 'insumo'
                                                  ON DELETE RESTRICT
);

-- Índices para otimizar as buscas por relatórios de consumo
CREATE INDEX idx_consumo_evolucao ON clinica.consumos_insumos(evolucao_id);
CREATE INDEX idx_consumo_insumo ON clinica.consumos_insumos(insumo_id);