CREATE TABLE agendamento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    paciente_id      BIGINT                                  NOT NULL,
    profissional_id  BIGINT                                  NOT NULL,
    procedimento_id  BIGINT                                  NOT NULL,
    data_hora_inicio TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    data_hora_fim    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status           VARCHAR(255),
    motivo_consulta  VARCHAR(255),
    valor_previsto   DECIMAL,
    CONSTRAINT pk_agendamento PRIMARY KEY (id)
);

CREATE TABLE evolucoes_clinicas
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao           TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao       TIMESTAMP WITHOUT TIME ZONE,
    ativo                  BOOLEAN,
    agendamento_id         BIGINT                                  NOT NULL,
    paciente_id            BIGINT                                  NOT NULL,
    profissional_id        BIGINT                                  NOT NULL,
    data_registro          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    relato_clinico         TEXT                                    NOT NULL,
    diagnostico_hipotetico VARCHAR(255),
    CONSTRAINT pk_evolucoes_clinicas PRIMARY KEY (id)
);

CREATE TABLE insumo
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao       TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao   TIMESTAMP WITHOUT TIME ZONE,
    ativo              BOOLEAN,
    nome               VARCHAR(255),
    quantidade_estoque DOUBLE PRECISION,
    unidade_medida     VARCHAR(255),
    CONSTRAINT pk_insumo PRIMARY KEY (id)
);

CREATE TABLE local_aplicacao
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    nome             VARCHAR(255)                            NOT NULL,
    pre_definido     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_localaplicacao PRIMARY KEY (id)
);

CREATE TABLE paciente
(
    id                 BIGINT NOT NULL,
    observacoes_gerais VARCHAR(255),
    tipo_sanguineo     VARCHAR(255),
    nome_responsavel   VARCHAR(255),
    CONSTRAINT pk_paciente PRIMARY KEY (id)
);

CREATE TABLE pessoa
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    nome             VARCHAR(255),
    cpf              VARCHAR(255),
    email            VARCHAR(255),
    telefone         VARCHAR(255),
    data_nascimento  date,
    logradouro       VARCHAR(255),
    numero           VARCHAR(255),
    complemento      VARCHAR(255),
    bairro           VARCHAR(255),
    cidade           VARCHAR(255),
    estado           VARCHAR(255),
    cep              VARCHAR(255),
    CONSTRAINT pk_pessoa PRIMARY KEY (id)
);

CREATE TABLE procedimento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    nome             VARCHAR(255)                            NOT NULL,
    preco_sugerido   DECIMAL,
    duracao_minutos  INTEGER,
    CONSTRAINT pk_procedimento PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao          TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao      TIMESTAMP WITHOUT TIME ZONE,
    ativo                 BOOLEAN,
    login                 VARCHAR(255)                            NOT NULL,
    senha                 VARCHAR(255)                            NOT NULL,
    nome                  VARCHAR(255)                            NOT NULL,
    email                 VARCHAR(255),
    perfil                VARCHAR(255),
    registro_profissional VARCHAR(255),
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE evolucoes_clinicas
    ADD CONSTRAINT uc_evolucoes_clinicas_agendamento UNIQUE (agendamento_id);

ALTER TABLE local_aplicacao
    ADD CONSTRAINT uc_localaplicacao_nome UNIQUE (nome);

ALTER TABLE pessoa
    ADD CONSTRAINT uc_pessoa_cpf UNIQUE (cpf);

ALTER TABLE procedimento
    ADD CONSTRAINT uc_procedimento_nome UNIQUE (nome);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_login UNIQUE (login);

ALTER TABLE agendamento
    ADD CONSTRAINT FK_AGENDAMENTO_ON_PACIENTE FOREIGN KEY (paciente_id) REFERENCES paciente (id);

ALTER TABLE agendamento
    ADD CONSTRAINT FK_AGENDAMENTO_ON_PROCEDIMENTO FOREIGN KEY (procedimento_id) REFERENCES procedimento (id);

ALTER TABLE agendamento
    ADD CONSTRAINT FK_AGENDAMENTO_ON_PROFISSIONAL FOREIGN KEY (profissional_id) REFERENCES usuarios (id);

ALTER TABLE evolucoes_clinicas
    ADD CONSTRAINT FK_EVOLUCOES_CLINICAS_ON_AGENDAMENTO FOREIGN KEY (agendamento_id) REFERENCES agendamento (id);

ALTER TABLE evolucoes_clinicas
    ADD CONSTRAINT FK_EVOLUCOES_CLINICAS_ON_PACIENTE FOREIGN KEY (paciente_id) REFERENCES paciente (id);

ALTER TABLE evolucoes_clinicas
    ADD CONSTRAINT FK_EVOLUCOES_CLINICAS_ON_PROFISSIONAL FOREIGN KEY (profissional_id) REFERENCES usuarios (id);

ALTER TABLE paciente
    ADD CONSTRAINT FK_PACIENTE_ON_ID FOREIGN KEY (id) REFERENCES pessoa (id);

CREATE TABLE clinica.evolucao_locais
(
    evolucao_id BIGINT NOT NULL,
    local_id    BIGINT NOT NULL
);

CREATE TABLE clinica.evolucoes_esteticas
(
    id               BIGINT NOT NULL,
    numero_sessao    INTEGER,
    dose_aplicada_mg DOUBLE PRECISION,
    peso_paciente_kg DOUBLE PRECISION,
    CONSTRAINT pk_evolucoes_esteticas PRIMARY KEY (id)
);

ALTER TABLE clinica.evolucoes_esteticas
    ADD CONSTRAINT FK_EVOLUCOES_ESTETICAS_ON_ID FOREIGN KEY (id) REFERENCES evolucoes_clinicas (id);

ALTER TABLE clinica.evolucao_locais
    ADD CONSTRAINT fk_evoloc_on_evolucao_estetica FOREIGN KEY (evolucao_id) REFERENCES clinica.evolucoes_esteticas (id);

ALTER TABLE clinica.evolucao_locais
    ADD CONSTRAINT fk_evoloc_on_local_aplicacao FOREIGN KEY (local_id) REFERENCES local_aplicacao (id);