-- Caixa / pagamentos
CREATE TABLE clinica.pagamento
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao       TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao   TIMESTAMP WITHOUT TIME ZONE,
    ativo              BOOLEAN,
    agendamento_id     BIGINT                                  NOT NULL,
    valor_bruto        DECIMAL(12, 2)                          NOT NULL,
    desconto           DECIMAL(12, 2)                          NOT NULL DEFAULT 0,
    valor_pago         DECIMAL(12, 2)                          NOT NULL,
    forma_pagamento    VARCHAR(40)                             NOT NULL,
    status             VARCHAR(40)                             NOT NULL,
    data_pagamento     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    observacao         VARCHAR(500),
    registrado_por_id  BIGINT,
    CONSTRAINT pk_pagamento PRIMARY KEY (id),
    CONSTRAINT fk_pagamento_agendamento FOREIGN KEY (agendamento_id) REFERENCES clinica.agendamento (id),
    CONSTRAINT fk_pagamento_registrado_por FOREIGN KEY (registrado_por_id) REFERENCES clinica.usuarios (id)
);

CREATE TABLE clinica.pagamento_item
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
    ativo            BOOLEAN,
    pagamento_id     BIGINT                                  NOT NULL,
    procedimento_id  BIGINT,
    descricao        VARCHAR(255)                            NOT NULL,
    valor_unitario   DECIMAL(12, 2)                          NOT NULL,
    quantidade       INTEGER                                 NOT NULL DEFAULT 1,
    CONSTRAINT pk_pagamento_item PRIMARY KEY (id),
    CONSTRAINT fk_pagamento_item_pagamento FOREIGN KEY (pagamento_id) REFERENCES clinica.pagamento (id) ON DELETE CASCADE,
    CONSTRAINT fk_pagamento_item_procedimento FOREIGN KEY (procedimento_id) REFERENCES clinica.procedimento (id)
);

CREATE INDEX idx_pagamento_data ON clinica.pagamento (data_pagamento);
CREATE INDEX idx_pagamento_agendamento ON clinica.pagamento (agendamento_id);
CREATE INDEX idx_pagamento_status ON clinica.pagamento (status);
CREATE INDEX idx_pagamento_forma ON clinica.pagamento (forma_pagamento);

-- Procedimentos sem preço passam a 0 e o campo vira obrigatório
UPDATE clinica.procedimento SET preco_sugerido = 0 WHERE preco_sugerido IS NULL;
ALTER TABLE clinica.procedimento ALTER COLUMN preco_sugerido SET NOT NULL;
